apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName}}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName}}
  template:
    metadata:
      labels:
        app: {{ .Values.appName}}
    spec:
      containers:
        - name: {{ .Values.appName}}
          # takia111/new0-image:latest--> values.yaml divides it into image and tag sub-chart
          image: "{{ .Values.image.name}}:{{ .Values.image.tag}}"
          ports:
            - containerPort: 8080
          args:
            {{- range $value := .Values.args }}
            - {{ $value | quote}}
            {{- end}}